### ISSUE TITLE
Brave browser has trouble with extension to save settings of it

### ISSUE THREAD

**Issue by Dean-Corso** [sandboxie-plus/Sandboxie#1095]
**Describe the bug**
I'am trying to use the Brave browser with an extension called "Highlight This".The problem is that the settings & words you can save in the extension getting not saved anymore.When you close the Brave browser and re-start it in Sandboxie then the extension was set back to default (all words are gone).I tried to check out that problem a little and found some possible write to file issue in that folder...
`\Local\BraveSoftware\Brave-Browser\User Data\Default\Local Storage\`
...and the extension seems to create a folder called "leveldb" to store/log setting infos inside.Normaly if you do add any word in the extension then the change gets written into one of those files stored in the "leveldb"  folder.So in my case its a file called "000003.log".In the case of running Brave in SB it does not happen and nothing gets written to the file.Now when I close Brave then all file which are stored in the "leveldb" folder getting changed to 0 bytes files and  can also not accessed and Windows said file not found whats really strange and the creation date of those files having the date of 1986!The brave brwoser did create another folder called "leveldb__tmp_for_rebuild" after closing which seems to be a backup etc.

I found out that this problem also happens with older SB versions too.The last working one is "SandboxieInstall64-v5.45.2" and  newer version after making that trouble too.

**To Reproduce**
1. Install Sandboxie-Classic-x64-v5.51.3
2. Install Brave Browser x64 (Version 1.27.111 Chromium: 92.0.4515.131 (Official Build) (64-bit)) outside of SB
3. Install the "Highlight This" extension
`https://highlightthis.net/`
or
`https://chrome.google.com/webstore/detail/highlight-this-finds-and/fgmbnmjmbjenlhbefngfibmjkpbcljaj`
4. Start Brave browser in any of your Sandbox
5. Add some word/s into "Highlight This" extension and press save
6. Exit Brave and re-start Brave again in same SB
7. Check your wordlist in "Highlight This" extension and you will see its empty
8. Have a look into the folder path in your SB
`C:\Sandbox\**YourUserName**\**SandBoxName**\user\current\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Local Storage`
Inside of this path you will see the folders "leveldb" & "leveldb__tmp_for_rebuild" which gets created in case of any problem.
9. Look into the leveldb folder and you should see few files which have the size of 0

**Expected behavior**
Brave / Extension dosen't save the added words & settings you did in the extension itself.If you re-start Brave then all is gone.Maybe you have to do this start / re-start twice on the first time.

**System details and installed software (please provide the following information):**
OS: Win 10 x64 Version 20H2 (Build 19042.1165)
Sandboxie: Sandboxie-Classic-x64-v5.51.3
Brave: Version 1.27.111 Chromium: 92.0.4515.131 (Official Build) (64-bit)
Extension: Highlight This v5.2.3
No AntiVirus or any other security software used

**Additional context**
The problem dosen't happen in Firefox with same AddOn.In that case all is working in SB and words getting also saved in realtime into the "webappsstore.sqlite" file.Only Brave has that issue.

**Sandboxie configuration**
I just installed any classic version with upgrade option.With that method I do update my Sandboxie or downgrade it back.

**Comment by Dyras** [comment]
Hmmm does it work with Chrome?

**Comment by Dean-Corso** [comment]
I installed Chrome, ChromePortable, BravePortable and they are working correctly in the Sandbox.Only the Brave browser I have installed (Online Installer not portable) makes this trouble.Thats strange.I also tried to reset the complete Brave Browser settings but this didn't help.So what could be the reason for that problem?Maybe something in the Templates.ini?I didn't change anything in that file.So if I downgrade Sandboxie back to version "SandboxieInstall64-v5.45.2" then all is working fine again.I also tried the same in VirtualBox with same OS (not latest Win) / SB / Brave and there I get the same trouble.Somehow the installed version of Brave & SB having a problem.Below a image of the files in that folder getting changed to 0 bytes if I close Brave and the another folder leveldb__tmp_for_rebuild gets created (not in normal case).The files getting then no more changed on next run of Brave and they keep zero.I also can not open any of those files and WIndows said can't find that file etc.Somehow strange.Maybe anyone of you can check this out with any latest Brave 64 & latest SB.As I said, I get the same results in Vbox too.I think its really any bug in SB or just some Template entry or anything like that with Brave.I have seen that in the old Templates.ini of version "SandboxieInstall64-v5.45.2" is nothing set with the Brave browser but in the newer Templates.ini there are almost same entrys like for Chrome to find.Maybe there is something not correctly for 100% or so.Just check this out guys.
![SB_2021-08-11_215121](https://user-images.githubusercontent.com/88513086/129094652-cb5e0796-c741-4071-8da7-b12c428733d5.png)

**Comment by Dean-Corso** [comment]
Ok listen, I did some more tests in my VirtualBox playing around with latest SB version & latest installed Brave browser.As I said I get the trouble above (see image).Now I told you that I think that the problem could be some entry/s in the Templates.ini file and before trying to find a possible bad entry/s I just closed my running Sandboxie process and just changed the original Templates.ini file with the Templates.ini of the old working version "SandboxieInstall64-v5.45.2" (original file) and did started Sandboxie new and created a new fresh Sandbox where I did started the Brave browser and "oh wonder" its working and the files (see image above / pre post) are getting no more changed to 0 bytes.Thats the good news so the bug must be inside of the default Templates.ini file somewhere.Of course I'am getting now some errors from SB itself about some template problems....
> SBIE1411 Sandbox DefaultBox verweist auf eine unbekannte Vorlage (Template) RpcPortBindings
SBIE1411 Sandbox Z1 verweist auf eine unbekannte Vorlage (Template) RpcPortBindings
SBIE1411 Sandbox Z2 verweist auf eine unbekannte Vorlage (Template) RpcPortBindings
SBIE1411 Sandbox TemplateSettings verweist auf eine unbekannte Vorlage (Template) RpcPortBindings
SBIE1411 Sandbox DefaultBox verweist auf eine unbekannte Vorlage (Template) OpenSmartCard
SBIE1411 Sandbox DefaultBox verweist auf eine unbekannte Vorlage (Template) OpenBluetooth
SBIE1411 Sandbox DefaultBox verweist auf eine unbekannte Vorlage (Template) SkipHook
SBIE1411 Sandbox DefaultBox verweist auf eine unbekannte Vorlage (Template) FileCopy
SBIE1411 Sandbox Z1 verweist auf eine unbekannte Vorlage (Template) OpenSmartCard
SBIE1411 Sandbox Z1 verweist auf eine unbekannte Vorlage (Template) OpenBluetooth
SBIE1411 Sandbox Z1 verweist auf eine unbekannte Vorlage (Template) SkipHook
SBIE1411 Sandbox Z1 verweist auf eine unbekannte Vorlage (Template) FileCopy
SBIE1411 Sandbox Z2 verweist auf eine unbekannte Vorlage (Template) OpenSmartCard
SBIE1411 Sandbox Z2 verweist auf eine unbekannte Vorlage (Template) OpenBluetooth
SBIE1411 Sandbox Z2 verweist auf eine unbekannte Vorlage (Template) SkipHook
SBIE1411 Sandbox Z2 verweist auf eine unbekannte Vorlage (Template) FileCopy

...because I'am using the old one with the latest SB version etc.Maybe you can check this.

**Comment by DavidXanatos** [comment]
> Now when I close Brave then all file which are stored in the "leveldb" folder getting changed to 0 bytes files and can also not accessed and Windows said file not found whats really strange and the creation date of those files having the date of 1986!
>

this is how sandboxie marks files as deleted which exist outside teh box
so that if you delete a file in the box that exists outside teh box it will be seen as deleted.

Good to know that its template related, can you confirm that while SandboxieInstall64-v5.45.2 works already the successor Sandboxie-Classic-x64-v5.46.0.exe breaks the functionality?

**Comment by Dean-Corso** [comment]
I did some more tests now in VBox.I tried to uninstall the entire installed SB / re-boot and did install the latest SB version fresh on it and somehow it works now and the files getting not deleted anymore but I have no clue why!=?Thats maybe the good news that it seems to work in VBox but the problem is that its still NOT working on my main Windows 10 x64 OS.I tried to do the same steps as in VBox and uninstalled / re-boot / installed fresh but here its not working and the files getting still deleted anyway if I use a older SBbox or a new created SBox.The only diffrent I can see between my main OS & VBox OS is the Win 64 version.In VBox I'am using this version of Win 10 x64....
`Version 1909 (Build 18363.1316)`
....and on my main OS this...
`Version 20H2 (Build 19042.1165)`
...but I'am not sure whether this could be a reason for that problem.

Update: I made some another more tests on my main OS trying to install (upgrade method) many version I did download already.Below a list what I get after installing & testing.

**********************************************************
SandboxieInstall64-v5.45.2
-----------------------------
Brave about version check = Fails
An error occurred while checking for updates: Es konnte keine Verbindung zum Internet hergestellt werden. Falls Sie eine Firewall verwenden, setzen Sie bitte "BraveUpdate.exe" auf die weiße Liste. (error code 7: 0x800706D8 -- system level).
Learn more

IDM Integration Works (Checking Youtube)
Highlight This extension: Save words / settings = Works
Files getting not zero / deleted

Sandboxie-Classic-x64-v5.46.0
-----------------------------
Brave about version check = Fails
IDM Integration Works (Checking Youtube)
Highlight This extension: Save words / settings = Works
Files getting not zero / deleted

Sandboxie-Classic-x64-v5.46.1
-----------------------------
Brave about version check = Fails
IDM Integration Works (Checking Youtube)
Highlight This extension: Save words / settings = Works
Files getting not zero / deleted

Sandboxie-Classic-x64-v5.46.3
-----------------------------
Brave about version check = Fails
IDM Integration Works (Checking Youtube)
Highlight This extension: Save words / settings = Works
Files getting not zero / deleted

Sandboxie-Classic-x64-v5.46.4
-----------------------------
Sandboxie dosen't get started after upgrade / Have to start it manually
Brave about version check = Fails
IDM Integration Works (Checking Youtube)
Highlight This extension: Save words / settings = Works
Files getting not zero / deleted

Having problem to close 4 processes / see image
Takes a longer while til closing them

Sandboxie-Classic-x64-v5.46.5
-----------------------------
Sandboxie dosen't get started after upgrade / Have to start it manually
Brave about version check = Fails
IDM Integration Works (Checking Youtube)
Highlight This extension: Save words / settings = Works
Files getting not zero / deleted

Having problem to close 4 processes / see image
Takes a longer while til closing them

Sandboxie-Classic-x64-v5.49.0
-----------------------------
Everything fails to run Brave / see image 2
Nothing gets loaded successfully
Having problem to close 4 processes & Brave processes too
This SB version was a total fail

Sandboxie-Classic-x64-v5.49.7
-----------------------------
Everything fails to run Brave / see image 2
Nothing gets loaded successfully
Having problem to close 4 processes & Brave processes too / Manually exit
This SB version was a total fail
This version did create a leveldb__tmp_for_rebuild folder the first time

SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2203 Fehler bei der Kommunikation mit dem Sandboxie-Dienst: *GUIPROXY_00000001; MsgId: 15 - WerFault.exe [FF000000]
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1
SBIE2101 OpenProcess (C0000022) access=001FFFFF initialized=1

Sandboxie-Classic-x64-v5.49.8   <---- Trouble with files
-----------------------------
No extension errors like above / seems to work
IDM Integration Works (Checking Youtube)
Does create folder called leveldb__tmp_for_rebuild & does zero all files in leveldb folder

Sandboxie-Classic-x64-v5.50.2   <---- 
-----------------------------
IDM Integration NO MORE WORKING / SHOWING
Highlight This extension: Save words / settings = NOT working
Files getting ZERO / Deleted

Sandboxie-Classic-x64-v5.50.8   <---- Good but IDM fails
-----------------------------
IDM Integration NO MORE WORKING / SHOWING
Highlight This extension: Save words / settings = Works again
Files getting NOT ZERO / Deleted

Sandboxie-Classic-x64-v5.50.9   <---- Good but IDM fails
-----------------------------
IDM Integration NO MORE WORKING / SHOWING
Highlight This extension: Save words / settings = Works again
Files getting NOT ZERO / Deleted

Sandboxie-Classic-x64-v5.51.3   <---- IDM works but Zero files problem
-----------------------------
IDM Integration = Works again in this version
Highlight This extension: Save words / settings = NOT working
Files getting ZERO / Deleted
**********************************************************
Below 2 images I made.First one is from v5.46.4 which starts to have problems to close those processes straight.
![v5 46 4](https://user-images.githubusercontent.com/88513086/129275071-bff9255c-8f83-45a6-a4fb-11b3ac14ac1b.png)
This image below is from version v5.49.0 where nothing works with Brave.
![v5 49 0](https://user-images.githubusercontent.com/88513086/129275268-f5a22047-f5c2-4fcd-8160-070b803894b8.png)
As you can see there are mostly many diffrents.So what you can do is to check out this 2 versions....

Sandboxie-Classic-x64-v5.50.9   <---- Good but IDM fails
-----------------------------
IDM Integration NO MORE WORKING / SHOWING
Highlight This extension: Save words / settings = Works again
Files getting NOT ZERO / Deleted

Sandboxie-Classic-x64-v5.51.3   <---- IDM works but Zero files problem
-----------------------------
IDM Integration = Works again in this version
Highlight This extension: Save words / settings = NOT working
Files getting ZERO / Deleted

...so both version using the same Templates.ini file content (no diffrents to find using WinMerge).The first 5.50.9 works and no files getting deleted (leveldb folder) BUT the IDM integration does NOT work.In the other newer version 5.51.3 the IDM integration works BUT files (leveldb folder) gets zero / deleted.Maybe you can find any smaller diffrents between those 2 (stable/verify/NotPre) versions.I really don't have any clue anymore or getting out of clues now.Maybe my infos will help to find the possible reason to fix it in any next version or posting any workaround or something.Now I switched again back to version "Sandboxie-Classic-x64-v5.46.3" which seems to work same like "SandboxieInstall64-v5.45.2".

By the way, if you have some idea/s what I could try then just tell me.As I said, the template files of the 2 version above are same and this case the problem should be in your code maybe.Just have a look whether you can find anything.Thanks.

**Comment by Dean-Corso** [comment]
I still have same trouble in latest version "Sandboxie-Classic-x64-v5.51.4".

I found out some new things.The problem seems not to be any extensions I do install so the problem that the files getting deleted in the "leveldb" & creating the "leveldb__tmp_for_rebuild" on Brave browser exit.So it also happens by just setting some settings in Brave itself (outside of SB) and starting then this Brave in a SB.Then happens the same (files deleted).Pretty strange but I found a little workaround I can do to prevent that deleting behavior.The only thing I can / have to do is to rename (disable) the "User Data" folder on my main OS...
`X:\Users\YourName\AppData\Local\BraveSoftware\Brave-Browser\`
...and to delete the 2 folders...
`leveldb
&
leveldb__tmp_for_rebuild`
...in the Sandboxie itself...
`X:\Sandbox\YourName\BraveSB\user\current\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Local Storage\`
...and start Brave in this SB again.Now the files getting no more deleted and changes getting also saved so that I can keep using extensions like "HighLight This" normaly.Its a little detour I have to do to but with this method its working to use Brave in SB like in older versions (as I told before).

The main question is still why newer Sandboxie versions do delete thos files?The files getting also not deleted if I run Brave outside of SB = normal state but inside the Box on Brave exit they get deleted.Normaly SB should only delete files if I use the option to delete content in SB etc right.

Of course that behavior of newer SB versions is a little bad but so long I don't wanna use / run Brave browser itself outside of a Sandboxie I can use my found workaround so long til you guys found out that problem.

**Comment by DavidXanatos** [comment]
please try the latest build and let me know if it improved the situation

**Comment by DavidXanatos** [comment]
I tested it, installes brave unsandboxed, set up some highlights,
clsoed it, ran it sandboxed, added a new highlight list, closed it again 
opened it agian sandboxed and the new highlight list was still there.
I think the issue is solved

**Comment by Dean-Corso** [comment]
I tried the latest version Sandboxie-Classic-x64-v5.53.0 but the problem isn't solved only changed.Now the wordlist I have created outside of Sandbox gets copied into Sandbox (Normal on first run).If I change the wordlist now in Brave browser inside of SB then all is fine so far on first view but if you NOW run Brave browser again outside of SB & close and start NOW again inside of SB then the wordlist is changed with same words from HighLightThis of outside.So the wordlist was just copied or restored again from outside to inside and all words I had before inside of SB are gone.Its almost same problem as before only with the diffrent that now the whole wordlist of outside SB gets copied into inside SB and before it was just getting empty.Problem still is present.

But at the moment I see that this problem only happens when I'am using my older "User Data" Brave profile in the SB.I tried same with fresh profile outside & inside and there seems to keep all correctly seperated.Thats strange.When I'am using my old profile then its always creating the "leveldb__tmp_for_rebuild" folder and deletes the leveldb folder and on restart the wordlist of outside Brave version (HLThis) is again present in SB Brave.The only way to use my old profile correctly (with HLT extension) is to disable / rename the "User Data" folder outside and not using it anymore (no more run Brave outside or rename that User Data folder after) and then all keeps working fine.

I will try to keep this problem in mind and trying to do some more tests and send feedback if I find something new.Otherwise for the moment I can just say it works for new created profiles and only it fails with my older profile (backup I did copy into new SB) which is pretty large (all my stuff inside etc).
