### ISSUE TITLE
League of Legends Client black screen

### ISSUE THREAD

**Issue by StoneMoe** [sandboxie-plus/Sandboxie#1140]
**Describe the bug**
League of Legends matchmaking client window is totally black.

**To Reproduce**
1. Login game
2. Matchmaking window is totally black
3. Error log output in `debug.log`

**Expected behavior**
It works well.

**Screenshots**
![image](https://user-images.githubusercontent.com/5786577/130987158-fcb3c682-3709-4b86-a5f5-8ff844b91a88.png)

**System details and installed software:**
 - Windows 10 Pro Workstation Edition (10.0.19043 Build 19043)
 - Sandboxie Plus 0.9.4
 - League of Legends matchmaking client v11.17.393.2626
 - Windows Defender is enabled

**Additional context**
Previous game version works well, got this issue after upgrading to latest game version.

**Game log**
logs in `LeagueClient\debug.log`, which is wrote by `LeagueClientUx.exe`/`LeagueClientUxRender.exe`
```
[0826/225500.745:ERROR:simple_backend_impl.cc(757)] Simple Cache Backend: wrong file structure on disk: 2 path: E:/LOL/LeagueClient/../Game/LCCache\Code Cache\wasm
[0826/225500.745:ERROR:simple_backend_impl.cc(757)] Simple Cache Backend: wrong file structure on disk: 2 path: E:/LOL/LeagueClient/../Game/LCCache\Code Cache\js
[0826/225500.835:ERROR:simple_backend_impl.cc(757)] Simple Cache Backend: wrong file structure on disk: 2 path: E:/LOL/LeagueClient/../Game/LCCache\Code Cache\wasm
[0826/225500.848:ERROR:simple_backend_impl.cc(757)] Simple Cache Backend: wrong file structure on disk: 2 path: E:/LOL/LeagueClient/../Game/LCCache\Code Cache\js
[0826/225500.860:ERROR:disk_cache.cc(184)] Unable to create cache
[0826/225500.860:ERROR:disk_cache.cc(184)] Unable to create cache
[0826/225501.142:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -202
[0826/225501.221:ERROR:gpu_process_host.cc(1002)] GPU process exited unexpectedly: exit_code=-2147483645
[0826/225501.221:WARNING:gpu_process_host.cc(1316)] The GPU process has crashed 1 time(s)
[0826/225501.224:ERROR:command_buffer_proxy_impl.cc(123)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
[0826/225501.549:WARNING:gpu_process_host.cc(1030)] Reinitialized the GPU process after a crash. The reported initialization time was 186 ms
[0826/225501.621:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -202
[0826/225501.663:INFO:CONSOLE(1)] "WebSocket event: OPEN", source: https://127.0.0.1:57961/fe/plugin-runner/rcp-fe-plugin-runner.js (1)
[0826/225501.664:INFO:CONSOLE(1)] "WAMP Handshake complete", source: https://127.0.0.1:57961/fe/plugin-runner/rcp-fe-plugin-runner.js (1)
[0826/225501.852:ERROR:gpu_process_host.cc(1002)] GPU process exited unexpectedly: exit_code=-2147483645
[0826/225501.852:WARNING:gpu_process_host.cc(1316)] The GPU process has crashed 2 time(s)
[0826/225502.170:WARNING:gpu_process_host.cc(1030)] Reinitialized the GPU process after a crash. The reported initialization time was 177 ms
[0826/225502.433:ERROR:gpu_process_host.cc(1002)] GPU process exited unexpectedly: exit_code=-2147483645
[0826/225502.433:WARNING:gpu_process_host.cc(1316)] The GPU process has crashed 3 time(s)
[0826/225502.671:ERROR:viz_main_impl.cc(160)] Exiting GPU process due to errors during initialization
[0826/225502.675:ERROR:browser_gpu_channel_host_factory.cc(160)] Failed to launch GPU process.
```

**Comment by isaak654** [comment]
Could you post the exact download link of the client, please?

**Comment by StoneMoe** [comment]
> Could you post the exact download link of the client, please?

League of Legends Tencent Edition:
https://down.qq.com/lol/dltools/LOL_V4.2.5.4_FULL_0_tgod_signed.exe

this issue occured after login :(

**Comment by christensennn** [comment]
I have the same problem.It returns SBIE2103.

**Comment by isaak654** [comment]
SBIE2103 indicates that a sandboxed program has requested to start a driver, and that the request was denied.
Which driver is it? It should be reported in the message.

**Comment by StoneMoe** [comment]
> SBIE2103 indicates that a sandboxed program has requested to start a driver, and that the request was denied.
> Which driver is it? The exact name should be reported in the message.
> 
> However, it looks like it was added a new Client anticheat without a clear mention on the 11.10 patch notes.

it try to load two drivers named "ace-base" and "ace-game", which should be TenProtect(Tencent's anticheat) as I know.
But these driver already in previous version of this game, and the game can be played really well even with failed driver loads and some game crash reporter pops up.

So I assume this is some sort of electron(chromium?) related issue and opened this issue :D

**Comment by ameaninglessname** [comment]
> 
> 
> SBIE2103 indicates that a sandboxed program has requested to start a driver, and that the request was denied.
> Which driver is it? The exact name should be reported in the message.
> 
> However, it looks like it was added a new Client anticheat without a clear mention on the 11.10 patch notes.

SGuard64.exe (11864): SBIE2103 Denied attempt to load system driver 'ace-base [Easy] (StartService)'
SGuard64.exe (11864): SBIE2103 Denied attempt to load system driver 'ace-game [Easy] (StartService)'

**Comment by sibalaxiii** [comment]
It turns out that I'm not the only one who has this problem...

**Comment by StoneMoe** [comment]
@isaak654 what can I do for you to help investigating?  I'm repairing my PC these days but will respond ASAP :D

**Comment by isaak654** [comment]
In order to take a log with Plus, you need to enable 'Trace Log' tab by opening 'Options' menu -> 'Trace Logging'.
Once enabled, you can reproduce your issue.
After reproducing it, just right click -> 'Copy Panel' to copy the full log and post it here:
![trace_log](https://user-images.githubusercontent.com/12372772/113529350-793af380-95c3-11eb-8d48-f9aab655b37a.png)

**Comment by ameaninglessname** [comment]
> 
> 
> In order to take a log with Plus, you need to enable 'Trace Log' tab by opening 'Options' menu -> 'Trace Logging'.
> Once enabled, you can reproduce your issue.
> After reproducing it, just right click -> 'Copy Panel' to copy the full log and post it here:
> ![trace_log](https://user-images.githubusercontent.com/12372772/113529350-793af380-95c3-11eb-8d48-f9aab655b37a.png)

I am getting this:
[Trace Logging.txt](https://github.com/sandboxie-plus/Sandboxie/files/7123110/Trace.Logging.txt)

**Comment by isaak654** [comment]
This line is before the first WillError you've got when you were running Client.exe:
`Client.exe (15544, 13368) - 00:34:32.072                 Ipc                      \Sessions\1\BaseNamedObjects\TenProtect3_Share_Data_15544` 

As suggestion, you may apply `ClosedIpcPath=\Sessions\*\BaseNamedObjects\TenProtect3_*` to your sandbox and try again. If it didn't work, replace `ClosedIpcPath` with `OpenIpcPath` and try again.

In case of failure, you could try the same with other Ipc(s) references or see also [Sandboxie Trace](https://sandboxie-plus.github.io/sandboxie-docs/Content/SandboxieTrace.html) if you need more debug output with `IpcTrace=ad` or `IpcTrace=*` (A and D mean allowed+denied access, * means log everything).  In case you notice a perfomance decrease, that's expected. On the Plus UI, you can find these options in Sandbox options -> Advanced Options -> Tracing tab.

If you need a brief summary of the various Resource Access settings:
https://sandboxie-plus.github.io/sandboxie-docs/Content/ResourceAccess.html

**Comment by christensennn** [comment]
Has anyone successfully entered?
I tried to find the line before the first WilError and apply some paths to the sandbox options.
![image](https://user-images.githubusercontent.com/42790204/132805606-753edea2-8a89-4181-851b-c6bc6563f43c.png)
Unfortunately it didn't work.

**Comment by isaak654** [comment]
Recently it was discovered a compatibility regression that was breaking another client-server game ([#1154](https://git.io/Ju2vt)), so you may try to downgrade to 0.9.0 and verify this.

**Comment by christensennn** [comment]
![image](https://user-images.githubusercontent.com/42790204/132863388-e242f80d-78ea-46ec-a8d9-c08fe0d2d5dc.png)
I downgraded it and tried,but still got black window and this
![image](https://user-images.githubusercontent.com/42790204/132863217-b40e1118-2b6b-43d0-956e-715a8f3f9bc8.png)
[trace.txt](https://github.com/sandboxie-plus/Sandboxie/files/7144222/trace.txt)

**Comment by isaak654** [comment]
The original reporter of this issue already stated that these driver were already blocked in previous version of this game, and that the game could be played really well even with failed driver loads and some game crash reporter.

**Comment by isaak654** [comment]
The original reporter of this issue already stated here that these drivers were already blocked in previous version of this game, and that the game could be played really well even with failed driver loads and some game crash reporter.

**Comment by isaak654** [comment]
The original author of this issue already stated here that these drivers were already blocked in previous version of this game, and that the game could be played really well even with failed driver loads and some game crash reporter.

Unfortunately I have nothing more to add, except debugging this issue further as explained above.

**Comment by StoneMoe** [comment]
I tried
```
OpenIpcPath=\Sessions\*\BaseNamedObjects\__COND*
OpenIpcPath=\Sessions\*\BaseNamedObjects\__IPC*
```
and even
```
OpenIpcPath=\*
OpenIpcPath=\Sessions\*\BaseNamedObjects\__COND*
OpenIpcPath=\Sessions\*\BaseNamedObjects\__IPC*
```
according to `LeagueClientUxRender.exe`'s log before it crash
<details>
  <summary>135 lines log</summary>
  
```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.528   Ipc        open          \Sessions\1\BaseNamedObjects\DBWinMutex                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.528   ComClass                 {6CA50344-051A-4DED-9779-A43305165E35} ?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.528   Ipc                      \Sessions\1\BaseNamedObjects\__ComCatalogCache__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.528   Ipc                      \BaseNamedObjects\__ComCatalogCache__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 19832) - 22:01:38.528   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:64:WilError_03_p0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 19832) - 22:01:38.528   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:64:WilError_03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 19832) - 22:01:38.528   Ipc        open          \KernelObjects\MaximumCommitCondition                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 19832) - 22:01:38.528   Ipc        Open          \KnownDlls32\clbcatq.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 19832) - 22:01:38.528   Ipc                      \Sessions\1\BaseNamedObjects\__ComCatalogCache__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
LeagueClientUxRender.exe (20528, 19832) - 22:01:38.528   Ipc                      \BaseNamedObjects\__ComCatalogCache__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 19832) - 22:01:38.528   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:168:WilStaging_02_p0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
LeagueClientUxRender.exe (20528, 19832) - 22:01:38.528   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:168:WilStaging_02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 19832) - 22:01:38.528   ComClass                 Windows.Media.MediaExtensionAppServices.MediaExtensionBroker                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.427   Pipe                     \Device\DeviceApi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.427   Ipc        Open          \KnownDlls32\cfgmgr32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.427   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:64:WilError_03_p0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.427   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:64:WilError_03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.427   Ipc                      \RPC Control\LRPC-3b9ebd466adba7b335                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClient.exe (8704, 7376) - 22:01:38.416             Pipe       open          \Device\Afd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.416   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:168:WilStaging_02_p0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.416   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:168:WilStaging_02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.406   Pipe       (2)           \Device\NamedPipe\crashpad_8704_MFLOZSTYHMJMMSII                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.406   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:64:WilError_03_p0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.406   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:64:WilError_03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.406   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:168:WilStaging_02_p0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.406   Ipc                      \Sessions\1\BaseNamedObjects\SM0:20528:168:WilStaging_02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 21576) - 22:01:38.406   Ipc                      \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_DcomLaunch                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.406   Ipc                      \Sessions\1\BaseNamedObjects\windows_shell_global_counters                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\SBIE_BOXED_ServiceInitComplete_RpcSs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____QU_CONN__64__8__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____AC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____RD_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____RD_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____RD_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____RD_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____WT_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____WT_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____WT_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____WT_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____CC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____CC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____CC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____CC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____QU_CONN__64__8__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____AC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____RD_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____RD_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____RD_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____RD_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____WT_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____WT_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____WT_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____WT_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____CC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____CC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____CC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____CC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____QU_CONN__64__8__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____AC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____RD_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____RD_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____RD_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____RD_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____WT_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____WT_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____WT_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____WT_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____CC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____CC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____CC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____CC_CONN__msg_to_tips_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____QU_CONN__64__8__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____AC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____RD_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____RD_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____RD_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____RD_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____WT_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____WT_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____WT_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____WT_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_HAN____IMP_WAITER____CC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_SEM____IMP_WAITER____CC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__COND_MTX____IMP_WAITER____CC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____SHM_WAITER____CC_CONN__tips_to_msg_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc                      \Sessions\1\BaseNamedObjects\__IPC_SHM____CA_CONN__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Pipe                     \Device\KsecDD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Pipe                     \Device\CNG                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Ipc        Open          \KnownDlls32\bcryptPrimitives.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.395   Pipe                     \Device\KsecDD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.365   Ipc                      \RPC Control\epmapper                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.354   Ipc        Open          \KnownDlls32\bcrypt.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
wegame.exe (9884, 19036) - 22:01:38.344                  Ipc                      \Sessions\1\BaseNamedObjects\SSO_APP_EXIST_MUTEX_ID_6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.313   Ipc        Open          \KnownDlls32\IMM32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.313   Ipc        Open          \KnownDlls32\SHCORE.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.313   Ipc        Open          \KnownDlls32\COMDLG32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.313   Ipc        Open          \KnownDlls32\SHLWAPI.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.313   Ipc        Open          \KnownDlls32\CRYPT32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.313   Ipc        Open          \KnownDlls32\WINTRUST.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\WS2_32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\SHELL32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\OLEAUT32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\user32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\msvcp_win.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\gdi32full.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\win32u.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\gdi32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\combase.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\ole32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\ucrtbase.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\rpcrt4.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\sechost.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\MSVCRT.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\advapi32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc                      \Sessions\1\BaseNamedObjects\SboxSession                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        open          \RPC Control\SbieSvcPort                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc                      \Sessions\1\BaseNamedObjects\SBIE_BOXED_DummyEvent_20528                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Drive                    \Device\HarddiskVolume9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Drive                    \Device\HarddiskVolume7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Drive                    \Device\HarddiskVolume8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Drive                    \Device\HarddiskVolume4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\PSAPI.DLL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \Sessions\1\Windows\ApiPort                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \Sessions\1\Windows\SharedSection                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\kernelbase.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\kernel32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls\wow64cpu.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls\user32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls32\kernel32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls\kernel32.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls\wow64win.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
LeagueClientUxRender.exe (20528, 18404) - 22:01:38.302   Ipc        Open          \KnownDlls\wow64.dll                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
LeagueClientUx.exe (21908, 8684) - 22:01:38.302          Pipe       (5)           \Device\NamedPipe\mojo.21908.8684.9600343279550506068                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClientUx.exe (21908, 19056) - 22:01:38.302         Debug      trace         CreateProcess: C:\Sandbox\StoneMoe\Tencent\drive\E\WeGameApps\LOL\LeagueClient\LeagueClientUxRender.exe ("C:\Sandbox\StoneMoe\Tencent\drive\E\WeGameApps\LOL\LeagueClient\LeagueClientUxRender.exe" --type=gpu-process --field-trial-handle=1944,4307739058712521616,13931153429468493489,131072 --disable-features=CookiesWithoutSameSiteMustBeSecure,HardwareMediaKeyHandling,SameSiteByDefaultCookies --no-sandbox --log-file="E:\WeGameApps\LOL\LeagueClient\debug.log" --user-agent="LeagueOfLegendsClient/11.18.396.9310 (CEF 91)" --lang=en-US --gpu-preferences=SAAAAAAAAADgAAAwAAAAAAAAAAAAAAAAAABgAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAKAAAAAQAAAAgAAAAAAAAACgAAAAAAAAAMAAAAAAAAAA4AAAAAAAAABAAAAAAAAAAAAAAAAUAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAABAAAABQAAABAAAAAAAAAAAQAAAAYAAAAIAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --log-file="E:\WeGameApps\LOL\LeagueClient\debug.log" --mojo-platform-channel-handle=2132 /prefetch:2 --app-name=LeagueClient --ux-name=LeagueClientUx --ux-helper-name=LeagueClientUxHelpe   
LeagueClientUx.exe (21908, 8684) - 22:01:38.302          Pipe       (4)           \Device\NamedPipe\mojo.21908.8684.4959215975331319476                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
LeagueClient.exe (8704, 13908) - 22:01:38.241            Ipc                      \Sessions\1\BaseNamedObjects\{36B087B4-B63F-456B-92CB-7AFE68A48404}      
```
</details>

but still not work :(

with `IpcTrace=*` enabled, log buffer seems be flooded
I'll try some other tracing configuration later


BTW I suddenly realized when the "game crash repoters" pops up in previous version of this game, is exactly at the same time as this black window appears. So I think game devs collected crash reports, decieded to ignore the crash and paint it all black :D

**Comment by ameaninglessname** [comment]
Would 1.0 solve this related issue?

**Comment by StoneMoe** [comment]
Trying to find some workaround but got no luck, both of these are not work(or I did it wrong):
1. patch libcef.dll to enable `--disable-gpu`
2. hook `CreateProcessW` `CreateProcessA` to add `--disable-gpu` command line for `LeagureClientUxRender.exe`

**Comment by StoneMoe** [comment]
![image](https://user-images.githubusercontent.com/5786577/140942847-32eb1615-ede0-45b3-ad00-22cda6efc55f.png)

I also tried League of Legends North America version
which is operating by Riot Games, no `TenProtect` included
and got excactly same result.

So I think this is not anti-cheat related problem

Download: https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe

**Comment by StoneMoe** [comment]
LeagueClientUxRender crash dump: 
[2d5c72c1-854f-4e8d-be44-4cc9cfe1a31b.zip](https://github.com/sandboxie-plus/Sandboxie/files/7505689/2d5c72c1-854f-4e8d-be44-4cc9cfe1a31b.zip)

libcef.dll:


WinDBG `!analyze -v` result:
```
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** WARNING: Unable to verify checksum for USER32.dll
*** WARNING: Unable to verify checksum for ole32.dll
*** WARNING: Unable to verify checksum for mf.dll
*** WARNING: Unable to verify checksum for MSVCP140.dll

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 3359

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 17281

    Key  : Analysis.Init.CPU.mSec
    Value: 1093

    Key  : Analysis.Init.Elapsed.mSec
    Value: 487139

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 138

    Key  : WER.Process.Version
    Value: 11.22.406.9787


FILE_IN_CAB:  2d5c72c1-854f-4e8d-be44-4cc9cfe1a31b.dmp

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

CONTEXT:  (.ecxr)
eax=00000000 ebx=00000000 ecx=02659ad5 edx=00000000 esi=5f262300 edi=0aaaf720
eip=131568fa esp=0aaaf720 ebp=0aaaf824 iopl=0         nv up ei pl nz ac po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000212
libcef+0x31a68fa:
131568fa cc              int     3
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 131568fa (libcef+0x031a68fa)
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 1
   Parameter[0]: 00000000

PROCESS_NAME:  LeagueClientUxRender.exe

ERROR_CODE: (NTSTATUS) 0x80000003 - {    }

EXCEPTION_CODE_STR:  80000003

EXCEPTION_PARAMETER1:  00000000

STACK_TEXT:  
WARNING: Stack unwind information not available. Following frames may be wrong.
0aaaf824 13156aa6     5f281894 00ede618 5f3b4880 libcef+0x31a68fa
0aaaf83c 12414b8a     5f281880 5f51c000 00000000 libcef+0x31a6aa6
0aaaf8b8 12d62945     16f7eca8 5f51c000 12440b76 libcef+0x2464b8a
0aaaf950 12d625d5     0aaaf978 0aaaf980 00000000 libcef+0x2db2945
0aaaf9c8 1243fc5b     0aaaf9e0 5f2ed304 00000004 libcef+0x2db25d5
0aaafa18 1243f527     5f2ed2b4 ffff0000 60ce339d libcef+0x248fc5b
0aaafa34 12d63019     5f2ed2b4 00000008 ffffffff libcef+0x248f527
0aaafa70 123fba42     00000001 ffffffff 7fffffff libcef+0x2db3019
0aaafabc 12428a78     0aaafac8 1692d0cd 16deb148 libcef+0x244ba42
0aaafae4 12428c00     0aaafb00 5f201440 00000000 libcef+0x2478a78
0aaafb34 1244761a     5f28ca20 00000ac8 60ce32fd libcef+0x2478c00
0aaafb54 7737fa29     5f2899f0 7737fa10 0aaafbc0 libcef+0x249761a
0aaafb64 77a77a9e     5f2899f0 ff6a89c2 00000000 kernel32!BaseThreadInitThunk+0x19
0aaafbc0 77a77a6e     ffffffff 77a98a3c 00000000 ntdll!__RtlUserThreadStart+0x2f
0aaafbd0 00000000     12447560 5f2899f0 00000000 ntdll!_RtlUserThreadStart+0x1b


SYMBOL_NAME:  libcef+31a68fa

MODULE_NAME: libcef

IMAGE_NAME:  libcef.dll

STACK_COMMAND:  ~49s ; .ecxr ; kb

FAILURE_BUCKET_ID:  BREAKPOINT_80000003_libcef.dll!Unknown

OSPLATFORM_TYPE:  x86

OSNAME:  Windows 10

IMAGE_VERSION:  91.1.22.0

FAILURE_ID_HASH:  {12df79a2-4c27-85df-b85c-2bc318e11fa3}

Followup:     MachineOwner
---------

```

**Comment by ameaninglessname** [comment]
https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.8
League of Legends is correctly running with latest version.

Thanks!

**Comment by StoneMoe** [comment]
> https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.8 League of Legends is correctly running with latest version.

Thanks for informing, I did more tests:
Plus x64 0.9.8d: not work
Plus x64 1.0.2: not work
Plus x64 1.0.3: works
Plus x64 1.0.8: works

since Chromium HW acceleration issue is resolved in v1.0.3, I think it's related.
huge thanks to developers actively maintaining!!

**Comment by R0uli078** [comment]
Hi ! It still doesn't work for me when I lauch a game. Only the Lol Client work.

**Comment by StoneMoe** [comment]
NOTICE: Tencent will ban your account for a month if you run LOL in sandbox for "game client modification"

**Comment by ameaninglessname** [comment]
> NOTICE: Tencent will ban your account for a month if you run LOL in sandbox for "game client modification"

Haven't experience it yet, i didn't play it within one or two week, version updated?

**Comment by Rithmatist** [comment]
> > https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.8 League of Legends is correctly running with latest version.
> 
> Thanks for informing, I did more tests: Plus x64 0.9.8d: not work Plus x64 1.0.2: not work Plus x64 1.0.3: works Plus x64 1.0.8: works
> 
> since Chromium HW acceleration issue is resolved in v1.0.3, I think it's related. huge thanks to developers actively maintaining!!

Hello, I am using the latest version of Sandboxie plus and I have EnableWin32kHooks=y on.
But When I start a game, It doesn't even open the screen just instant debug window, I will share my trace logs

**Comment by Rithmatist** [comment]
[trace.log](https://github.com/sandboxie-plus/Sandboxie/files/8890157/trace.log)
Here is my trace-log
