### ISSUE TITLE
Regressions with 5.52.x Classic builds

### ISSUE THREAD

**Issue by Seeadler1** [sandboxie-plus/Sandboxie#1249]
The second sandbox disappeared in the Classic version after this update. Only the default box is displayed in the Sandboxie control.

Regards

**Comment by Seeadler1** [comment]
The name of the second sandbox is: Sandbox2

**Comment by mysteriously** [comment]
For me one on few sandboxes also disappeared from classic sandboxie app window. I was still able to run apps in it using previously made shortcut. Reloading, deleting and adding Sandbox name didnt fix the issue.

Also after this update I noticed I had Chrome as forced app in 3 sandboxes. It worked for me for many months (Chrome default browser was opening in right sandbox). After the app update, I noticed the Chrome opens on other sandbox, which allowed me to fix the issue in settings.

**Comment by DavidXanatos** [comment]
https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.7b

**Comment by isaak654** [comment]
> 
> 
> https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.7b

It doesn't look fixed yet, according to some reports:
https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-7-test-build.440906/#post-3038593
https://www.wilderssecurity.com/threads/released-sandboxie-plus-sbie-fork-versions-with-signed-driver.434924/page-43#post-3038585

**Comment by DavidXanatos** [comment]
how about this: https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.7c

**Comment by bjm234** [comment]
> how about this: https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.7c

0.9.7c does not include SbieCtrl
https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-7-test-build.440906/page-2#post-3038734

**Comment by DavidXanatos** [comment]
Is anyone using it with the plus installation? I thought by now I coudl remove it and no one woudl notice.
But if that's still needed i can add it back with the next release.

**Comment by bjm234** [comment]
> Is anyone using it with the plus installation? I thought by now I coudl remove it and no one woudl notice. But if that's still needed i can add it back with the next release.

Oh....I must of missed the memo.  
I like SbieCtrl.  I'm okay with what ever works for you, works for users.

**Comment by isaak654** [comment]
Someone has a new issue on 5.52.3 that wasn't present on a clean install with 5.51.6:
https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-7-test-build.440906/page-2#post-3038839

**Comment by DavidXanatos** [comment]
I cant reproduce this issues can you?

**Comment by isaak654** [comment]
I can confirm partially this one on Classic 5.52.3:

> After all of the above, I decided to click Remove Sandbox and start over. The sandbox was not removed. I tried to rename it and strange things started to happen. I clicked Sandbox on the top menu and now there's invisible options in the dropdown menu.

In my specific case, I renamed a sandbox from `Saya` to `Saya2`, but instead of doing it, Sbiectrl.exe created a new sandbox named `Saya2` with the same ini lines of `Saya` in the opposite order (with all `Template=` references ordered to the bottom, while these references should be ordered to the top).

My Sandboxie.ini is located on the Sandboxie folder in %ProgramFiles% and it's encoded as UTF-16 LE BOM.

**Comment by isaak654** [comment]
I can confirm partially this one on Classic 5.52.3:

> After all of the above, I decided to click Remove Sandbox and start over. The sandbox was not removed. I tried to rename it and strange things started to happen. I clicked Sandbox on the top menu and now there's invisible options in the dropdown menu.

In my specific case, I attempted to rename a sandbox from `Saya` to `Saya2`, but instead of doing it, Sbiectrl.exe created a new sandbox named `Saya2` with the same ini lines of `Saya` in the opposite order (with all `Template=` references ordered to the bottom, while these references should be ordered to the top).

My Sandboxie.ini is located on the Sandboxie folder in %ProgramFiles% and it's encoded as UTF-16 LE BOM.

**Comment by isaak654** [comment]
I can confirm this one on Classic 5.52.3 / W10 20H2:

> After all of the above, I decided to click Remove Sandbox and start over. The sandbox was not removed. I tried to rename it and strange things started to happen. I clicked Sandbox on the top menu and now there's invisible options in the dropdown menu.

In my specific case I attempted to rename a sandbox from `Saya` to `Saya2`, but instead of doing it, Sbiectrl.exe created a new sandbox named `Saya2` with the same ini lines of `Saya` in the opposite order (with all `Template=` references ordered at the bottom of the sandbox section, while these references should be theoretically ordered at the top, after `Enabled=` and `ConfigLevel=`). In addition, I tried to rename `Saya2` to `Saya5` and I noticed that it failed the first time, while the second time it succeeded. 

Half of the time the renaming operation fails, and the "Remove Sandbox" operation doesn't get applied to the UI if you don't reload it. I would suggest to create a new sandbox and remove it after a few seconds... in this case you need to refresh the UI manually just to see it disappeared.

My Sandboxie.ini is located on the Sandboxie folder in %ProgramFiles% and it's encoded as UTF-16 LE BOM.

Abou the dropdown menu mentioned from that user, you could ask him if it's related to the visual glitch described here: https://github.com/sandboxie-plus/Sandboxie/issues/913
Even if it's not related, you may want to catch this occasion to fix it too.

**Comment by DavidXanatos** [comment]
this should fix it fo good: https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.7d

**Comment by isaak654** [comment]
> First lets fix all the actual bugs.

One relevant regression left (on both v0.9.7e / 5.52.5):
https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-7-test-build.440906/page-3#post-3039637

Please consider to fix the following Classic issue https://github.com/sandboxie-plus/Sandboxie/issues/913 if possible. 
I pushed a fix for it time ago, but it didn't produce any effect (https://github.com/sandboxie-plus/Sandboxie/pull/761).

**Comment by DavidXanatos** [comment]
this should be fixed with ine of the latest builds so i'll close it

**Comment by isaak654** [comment]
> 
> 
> this should be fixed with ine of the latest builds so i'll close it

[This](https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-7-test-build.440906/page-3#post-3039637) regression is still not fixed on v0.9.7e / 5.52.5, that appears to be the latest public build (till now).

> I have installed the new version on all my systems and it actually runs without any problems.
Only on one system there is a small problem. Whenever I open a file dialog (via "Open" or "Save") in a sandboxed program the following error message appears:
SBIE2101 CreateFile (C0000022) access=0012019F initialized=1
The program doesn't matter, it happens e.g. with Notepad, Firefox, Acrobat Reader... The error message can be ignored, everything still works. If the "Explorer" itself is opened in the sandbox, the error message does not appear. The problem occurs only from the current version 5.52.x (also 0.9.7x). With version 5.51.6 or previous versions the error message does not appear.
Any ideas what this could be related to? Thanks!
[Windows 10 21H1 (x64)] 

See also the confirmation sent by @APMichael today:
https://www.wilderssecurity.com/threads/sandboxie-plus-0-9-7-test-build.440906/page-4#post-3040149

>  Unfortunately, the error message is also with the Plus build without further information. :(
(So I could not find a solution myself, except to hide the error message.)
Good to hear that you already have an idea.

**Comment by DavidXanatos** [comment]
the message will be fixed in the next build
