### ISSUE TITLE
Unable to stop the driver in a regular way through the system service api

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [sandboxie-plus/Sandboxie#2392]
### Describe what you noticed and did

I try to stop the driver through SystemInformer and get an error:
Unable to stop SbieDrv.
The requested control is not valid for this service.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Driver shuts down properly.

### What is your Windows edition and version?

Windows 10 Pro 21H1 64 bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

1.5.0 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by bastik-1001** [comment]
Just in case this isn't a bug, but instead intended as a feature to protect the driver from being killed by accident AND this ticket being resolved by honoring the system service API, consider to make this an optional thing.

**Comment by DavidXanatos** [comment]
This is intentional you need to use the provided kmdutil tool like this "kmdutil stop sbiedrv" and unless you run "kmdutil stop sbiesvc" or "net stop sbiesvc" the driver will still fail to unload, it will generally fial to unload if any process is using it, you can use "kmdutil scandll" to terminate all processes using the sbiedll.dll ant those presumably holding a handle on the driver open.
