### ISSUE TITLE
Longtime Bug: Firefox High CPU usage ucrtbase.dll!beginthreadx+0x100

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#32]
This has been an ongoing buck for the last year or so, since 1809, still happens in windows x64 1909 and on different cpu/ram/mobo; to speed up the trigger, just open up 20-30 different unique tabs on RT.com rapidly, the bug should trigger and not go away. However, the program generally works fine for a while and will trigger no matter what page, no matter how little resources are loaded.  This basically makes sandboxie mostly useless for me ATM.

![Sandboxie 5 40 1 Bug](https://user-images.githubusercontent.com/38260267/82126970-2bc45680-9765-11ea-9c9a-bf9eaf414c21.png)

**Comment by rugabunda** [comment]
Same issue as mentioned in details here from multiple people: https://community.sophos.com/products/sandboxie/f/forum/116766/firefox-constant-25-cpu-usage-in-sandboxie

**Comment by rugabunda** [comment]
Just in case, for future reference, here is a backup: https://web.archive.org/web/20200517035708/https://community.sophos.com/products/sandboxie/f/forum/116766/firefox-constant-25-cpu-usage-in-sandboxie

**Comment by DavidXanatos** [comment]
thx will check that out currently I'm kind of buried in bug reports so that may take a while to get to to fix.

**Comment by menaquinoneK2** [comment]
Hi. About this issue. I've just spent a few hours trying to figure this out and only afterwards I find this very sandboxie issue.

So, what I found is that, Firefox is trying to delete the `trash*` dirs from within the `cache2` dir and for some reason, it doesn't even attempt to execute the delete command(DeleteFileW? or it's actually `SetDispositionInformationFile` with `Delete: True` - seen when outside of sandboxie does it, even though it is using `DeleteFileW` of `C:\Windows\System32\KernelBase.dll` seen in stacktrace by Process Monitor, and `RemoveDirectoryW` for the directory after the files are removed) and because it's coded with a `white true`, it keeps looping forever, as long as those `trash*` dirs exist. Should you remove them manually, then the 25% CPU usage stops.

https://bugzilla.mozilla.org/show_bug.cgi?id=968101#c20

I'm currently unsure why it works outside of sandboxie, it is able to find and delete them. But inside, apparently the deletion isn't even attempted(filtered by SetDispositionInformationFile in Process Monitor for example)! So, it could still be a firefox issue... I'm unsure.

The loop happens like this:
```
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 12272: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash13638
```

to see that I've had to set some environment variables:
```
C:\Program Files\Mozilla Firefox>set MOZ_LOG_FILE=log.txt
C:\Program Files\Mozilla Firefox>set MOZ_LOG=cache2:5
C:\Program Files\Mozilla Firefox>firefox -P
```

The `while true` code, in Firefox, is here: https://searchfox.org/mozilla-central/rev/6dc530332ceb86c9d196c1afe8ba5c90c26be898/netwerk/cache2/CacheFileIOManager.cpp#3364

I'm guessing that `file->Remove(isDir);` doesn't actually remove or even attempt to remove the file, iff it's even reached there. No idea. I can't compile firefox(or sandboxie), sorry.

This paste expires in 21 days but it shows how the looping happens(captured by Process Monitor): https://paste.mozilla.org/MK8ZFw3Z/raw

**Comment by DavidXanatos** [comment]
Interesting find I Will take a look on it,t hanks for the research.

**Comment by menaquinoneK2** [comment]
the sad part is, that I'm no longer able to reproduce the issue now. I tried placing `trash*` dirs there. I've even seen Firefox create new ones, and even from within sandboxie it was still able to find and delete them all now! I haven't upgraded Firefox(78.0b3 (64-bit)) or sandboxie(5.40.1 64bit) so I don't understand why it won't infinite loop anymore now! It's almost as if, it only gets stuck in certain conditions and once I've manually removed those `trash*` dirs once, it takes some special circumstances for the issue to happen again. So, I don't know how to re-trigger this, as it seems to be working now. And the deletion apparently happens via Operation `CreateFile` in Process Monitor, where the stacktrace can be seen to contain `RemoveDirectoryW` for dirs and `DeleteFileW` for the files within. There's no `SetDispositionInformationFile` (as Operation) anymore, but I could swear I've seen it happen before, during the same process of `trash*` files/dirs deletions process (just don't remember if it was outside or inside of sandboxie when I've seen it happen, but the latter case could only have been after my manual deletion of the `trash*` dirs after which I was unable to trigger this issue anymore ever since because it always kept working as intended aka trash dirs were getting (created and)deleted successfully). Is it possible it's using two different types of deletion? and it lately chose the one that works? I'm not even sure anymore.

So, if you ever get this issue, try to avoid removing the dirs manually, or else you risk being unable to re-create this issue. It's almost as if it seems fixed, but I could swear it cannot be... I even have firefox studies disabled(I think), so even firefox couldn't have fixed it behind my back.

I have no idea why it couldn't remove the `trash*` dirs before and it was thus infinite looping, but I KNOW that it was! And now, it seems to always work: it creates the dirs and removes them successfully now. Why? How? I must know...

**Comment by rugabunda** [comment]
Seems the cpu usage issue is fixed; after years and years of pleeding to sophos to no avail, DavidXanatos nailed it in a week. It seems, its been 12 hours or so without any issues; 

usually impossible to go 20 minutes without this issue re-occurring, and its a bug affecting thousands of people

GREAT WORK! You are doing an amazing job

**Comment by menaquinoneK2** [comment]
ah, the issue is back for me but I hadn't noticed it(due to silent enough fan), but to be clear I haven't yet updated sandboxie, I will after this and edit this comment to report.

But this time I won't be removing those `trash*` dirs because it's hard to reproduce this again! (but I know that it will stop CPU usage if I do remove them manually)
Any ideas?

**Comment by menaquinoneK2** [comment]
Maybe here's why firefox gets confused: I see _two_ different contents for that dir, when I look at it from within Total Commander vs when I look at it from within the sandbox. You may say this IS NORMAL ! and maybe it is... but I'm betting this is why firefox gets confused somehow!!

Actually there's **three** views now... 
when I run `explorer.exe` or `cmd.exe` from the host(not via sandboxie) while the current dir is `C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2` , it automatically gets the `[#] ... [#]` title showing me that it's actually ran `explorer` or `cmd` inside that sandbox! Both of these `cmd` and `explorer` apparently see the same content (ie. same files and dirs!), BUT, when I look via `cmd` and `total commander` from outside the host, they each see different contents even compared to the sandbox contents, not just themselves, so this is why I say there's three different views! I show below exactly.

So, 
**1) view one**:
this is what `dir` sees within `cmd.exe` (and same as `explorer.exe`) while it is sandboxed (eg. has `[#]` title)
```
 Directory of C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.defa
ult-beta\cache2

06/20/2020  11:38 AM    <DIR>          .
06/20/2020  11:38 AM    <DIR>          ..
06/19/2020  12:18 PM                 0 ce_Kg==
06/19/2020  12:18 PM                 0 ce_T151c2VyQ29udGV4dElkPTUs
06/19/2020  12:18 PM                 0 ce_T151c2VyQ29udGV4dElkPTUsYSw=
06/20/2020  11:45 AM    <DIR>          doomed
06/20/2020  11:45 AM    <DIR>          entries
06/20/2020  11:25 AM    <DIR>          trash10313
06/18/2020  23:55 PM    <DIR>          trash14175
06/20/2020  11:15 AM    <DIR>          trash1485
06/20/2020  11:37 AM    <DIR>          trash481
               3 File(s)              0 bytes
               8 Dir(s)   8,657,235,968 bytes free
```

**2) view two**:
this is what `cmd.exe` which is ran on the host (initially in `c:\` as current dir, let's say) and then chdir-ed to the `cache2` dir manually within:
```
 Directory of C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.defa
ult-beta\cache2

06/19/2020  12:18 PM    <DIR>          .
06/19/2020  12:18 PM    <DIR>          ..
06/19/2020  12:18 PM                 0 ce_Kg==
06/19/2020  12:18 PM                 0 ce_T151c2VyQ29udGV4dElkPTUs
06/19/2020  12:18 PM                 0 ce_T151c2VyQ29udGV4dElkPTUsYSw=
06/19/2020  12:18 PM    <DIR>          doomed
06/19/2020  12:18 PM    <DIR>          entries
06/18/2020  23:55 PM    <DIR>          trash14175
               3 File(s)              0 bytes
               5 Dir(s)   8,657,203,200 bytes free
```

**3) view three**
this is what `total commander` sees when it's running outside of any sandbox (just like cmd is running, on view two above):

![Clipboard01](https://user-images.githubusercontent.com/66539662/85198969-c6bbcd80-b2db-11ea-95f2-de21d6c200c8.jpg)
(you see those `ce_Kg==` files are not here)

And I've refreshed and re-ran those commands multiple times to ensure the contents remained as such, in all three views! even while firefox is now currently running with 25% cpu usage(aka one(of the four) core at full load).

So you see how all those views are different? I bet this is what trips up firefox while it's trying to do that background deletion of the trash dirs. I don't know how or why, but I did notice via Process Monitor that it does access that cache2 path in at least two ways, eg:
way one:
`C:\Sandbox\John\DefaultBox\user\current\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash1485`
way two:
`C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash1485`

which tells me that the last one is probably within sandbox? though I've no idea how it's able to access the outside of sandbox path... (as a process ie. firefox.exe, that's supposedly running inside sandboxie)

I used filter:
Process Name->is->`firefox.exe`
Path->contains->`cache2`

**Comment by DavidXanatos** [comment]
Not sure that this is wrong:

view 1 is inside the sand box which is a composite view of views 2 and 3

view 2 is the actual content of your unsandbox profile.

view 3 shows what was changed by the sandboxed firefox

View 3 is not supposed to contain any unchanged original files from view 2

Only when running sandboxes you see a combination of the real files with the captured alterations.


try the following, delete the original cache2, I assume you always run ff sandboxed so it shouldn't get re created and than watch if the issue re appears.
I presume its something around deleting and re creating folders with the same name, but on a short test I did not notice anything wrong

**Comment by menaquinoneK2** [comment]
Damn, I think I totally confused myself... allthewhile thinking that I'm showing the contents of dir `c:\Sandbox\John\DefaultBox\user\current\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2` from 3 views, but in fact I was also showing the host dir in view 2 ie. `C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2`

I'll need some time to review this again, so ignore what I said so far, it wasn't what I thought.

I do run Firefox outside of sandbox but only after updating it via its executable setup, then I try to update addons, then cleanup(ctrl+shift+del, all), exit. Then I delete the sandbox, run it in sandbox.

I deleted the trash dirs from host dir, but firefox was still using 25% CPU, then I deleted them from c:\Sandbox\.... but only the trash dirs, and it immediately stopped the CPU usage. All while writing this.

**Comment by rugabunda** [comment]
I have not had any re-occurance in nearly 48 hours. @menaquinoneK2 have you emptied your sandbox after upgrading and re-testing?

**Comment by menaquinoneK2** [comment]
I got more info since I've compiled firefox locally and can now muck around with it as I please...

Look at what happens that starts the infinite loop in firefox:

<details>

```
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::StartRemovingTrash()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::RemoveTrashInternal()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash15203
[Parent 18856: Cache2 I/O]: D/cache2 it's a file 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash15203\27323'
[Parent 18856: Cache2 I/O]: D/cache2 attempting remove of 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash15203\27323'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing file 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash15203\27323'
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash15203'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash15203'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash17007
[Parent 18856: Cache2 I/O]: D/cache2 it's a file 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007\15055'
[Parent 18856: Cache2 I/O]: D/cache2 attempting remove of 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007\15055'
[Parent 18856: Cache2 I/O]: D/cache2 failed(5) to remove file 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007\15055'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::RemoveTrashInternal() - Cannot remove trash file or dir. [name=15055] [absolutepath=C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007\15055]
[Parent 18856: Cache2 I/O]: D/cache2 it's a file 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007\15168'
[Parent 18856: Cache2 I/O]: D/cache2 attempting remove of 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007\15168'
[Parent 18856: Cache2 I/O]: D/cache2 failed(5) to remove file 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007\15168'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::RemoveTrashInternal() - Cannot remove trash file or dir. [name=15168] [absolutepath=C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007\15168]
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007'
[Parent 18856: Cache2 I/O]: D/cache2 failed(145) to remove dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash17007'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::RemoveTrashInternal() - Cannot remove trashdir. [name=trash17007]
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
```

</details>

using this patch:

<details>

```diff
diff --git a/netwerk/cache2/CacheFileIOManager.cpp b/netwerk/cache2/CacheFileIOManager.cpp
--- a/netwerk/cache2/CacheFileIOManager.cpp
+++ b/netwerk/cache2/CacheFileIOManager.cpp
@@ -3387,16 +3387,17 @@ nsresult CacheFileIOManager::RemoveTrash
       NS_ENSURE_SUCCESS(rv, rv);
 
       continue;  // check elapsed time
     }
 
     // We null out mTrashDirEnumerator once we remove all files in the
     // directory, so remove the trash directory if we don't have enumerator.
     if (!mTrashDirEnumerator) {
+		LOG(("no more stuff to enumerate, so removing parent dir (non-recursive) '%s'", mTrashDir->HumanReadablePath().get()));
       rv = mTrashDir->Remove(false);
       if (NS_FAILED(rv)) {
         // There is no reason why removing an empty directory should fail, but
         // if it does, we should continue and try to remove all other trash
         // directories.
         nsAutoCString leafName;
         mTrashDir->GetNativeLeafName(leafName);
         mFailedTrashDirs.AppendElement(leafName);
@@ -3408,16 +3409,17 @@ nsresult CacheFileIOManager::RemoveTrash
 
       mTrashDir = nullptr;
       continue;  // check elapsed time
     }
 
     nsCOMPtr<nsIFile> file;
     rv = mTrashDirEnumerator->GetNextFile(getter_AddRefs(file));
     if (!file) {
+		LOG(("got nothing more to enumerate"));
       mTrashDirEnumerator->Close();
       mTrashDirEnumerator = nullptr;
       continue;  // check elapsed time
     }
     bool isDir = false;
     file->IsDirectory(&isDir);
     if (isDir) {
       NS_WARNING(
@@ -3426,18 +3428,30 @@ nsresult CacheFileIOManager::RemoveTrash
       if (LOG_ENABLED()) {
         LOG(
             ("CacheFileIOManager::RemoveTrashInternal() - Found a directory in "
              "a trash "
              "directory! It will be removed recursively, but this can block IO "
              "thread for a while! [file=%s]",
              file->HumanReadablePath().get()));
       }
-    }
-    file->Remove(isDir);
+    } else {
+		LOG(("it's a file '%s'", file->HumanReadablePath().get()));
+	}
+	LOG(("attempting remove of '%s'", file->HumanReadablePath().get()));
+    rv = file->Remove(isDir);
+	if (NS_FAILED(rv)) {
+		nsAutoCString leafName;
+        file->GetNativeLeafName(leafName);
+        //mFailedTrashDirs.AppendElement(leafName);
+        LOG(
+            ("CacheFileIOManager::RemoveTrashInternal() - Cannot remove "
+             "trash file or dir. [name=%s] [absolutepath=%s]",
+             leafName.get(), file->HumanReadablePath().get()));
+      }
   }
 
   MOZ_ASSERT_UNREACHABLE("We should never get here");
   return NS_OK;
 }
 
 nsresult CacheFileIOManager::FindTrashDirToRemove() {
   LOG(("CacheFileIOManager::FindTrashDirToRemove()"));
diff --git a/xpcom/io/nsLocalFileWin.cpp b/xpcom/io/nsLocalFileWin.cpp
--- a/xpcom/io/nsLocalFileWin.cpp
+++ b/xpcom/io/nsLocalFileWin.cpp
@@ -54,16 +54,21 @@
 
 #include "mozIDOMWindow.h"
 #include "nsPIDOMWindow.h"
 #include "nsIWidget.h"
 #include "mozilla/ShellHeaderOnlyUtils.h"
 #include "mozilla/WidgetUtils.h"
 #include "WinUtils.h"
 
+//#include "mozilla/Printf.h" //for SmprintfPointer
+//extern mozilla::LazyLogModule gCache2Log;
+mozilla::LazyLogModule gCache2Log("cache2");
+#define LOG(x) MOZ_LOG(gCache2Log, mozilla::LogLevel::Debug, x)
+
 using namespace mozilla;
 using mozilla::FilePreferences::kDevicePathSpecifier;
 using mozilla::FilePreferences::kPathSeparator;
 
 #define CHECK_mWorkingPath()                                     \
   do {                                                           \
     if (mWorkingPath.IsEmpty()) return NS_ERROR_NOT_INITIALIZED; \
   } while (0)
@@ -2128,22 +2133,35 @@ nsLocalFile::Remove(bool aRecursive) {
         dirEnum->GetNext(getter_AddRefs(item));
         nsCOMPtr<nsIFile> file = do_QueryInterface(item);
         if (file) {
           file->Remove(aRecursive);
         }
       }
     }
     if (RemoveDirectoryW(mWorkingPath.get()) == 0) {
-      return ConvertWinError(GetLastError());
-    }
+		DWORD le=GetLastError();
+		LOG(("failed(%lu) to remove dir '%S'", le, mWorkingPath.get()));
+		//this didn't work (can't be seen anywhere)
+		//mozilla::SmprintfPointer msg = mozilla::Smprintf("failed to remove dir '%s'", mWorkingPath.get());
+		//NS_WARNING(msg.get());
+      return ConvertWinError(le);
+    } else {
+		LOG(("Succeeded in removing dir '%S'", mWorkingPath.get()));
+	}
   } else {
     if (DeleteFileW(mWorkingPath.get()) == 0) {
-      return ConvertWinError(GetLastError());
-    }
+		DWORD le=GetLastError();
+		LOG(("failed(%lu) to remove file '%S'", le, mWorkingPath.get()));
+		//mozilla::SmprintfPointer msg = mozilla::Smprintf("failed to remove file '%s'", mWorkingPath.get());
+		//NS_WARNING(msg.get());
+      return ConvertWinError(le);
+    } else {
+		LOG(("Succeeded in removing file '%S'", mWorkingPath.get()));
+	}
   }
 
   MakeDirty();
   return rv;
 }
 
 NS_IMETHODIMP
 nsLocalFile::GetLastModifiedTime(PRTime* aLastModifiedTime) { 
```

</details>

So the log shows how firefox started the process of removing the trash dirs and the first one it tries(`trash15203`) it succeeds in removing(I've verified that it's gone physically from disk also), the next one(`trash17007`) is a problematic one and cannot be removed(dno why yet) but as you can see, it tries to remove the 2 files which live inside it, which returns a [`GetLastError()`](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-?redirectedfrom=MSDN) of `5` (ERROR_ACCESS_DENIED    5 (0x5)    Access is denied. ) and then ignoring those errors, it tries to remove the dir(`trash17007`) itself(non-recursively! because firefox assumed that deleting the two files must've succeeded) and it yields `145` (ERROR_DIR_NOT_EMPTY    145 (0x91)    The directory is not empty.) as  `GetLastError()`, then it keeps moving on, and returns next dir(`trash22085`) and it apparently succeeded in removing(but not physically from the disk)! But then it keeps trying to find any other dirs, and it thus keeps finding this same dir(`trash22085`) over and over again due to `while true`, and it keeps "succeeding" to removing it, and yet it's not removed.

sandbox view is:
```
 Directory of C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.defa
ult-beta\cache2\trash17007

06/24/2020  02:17 AM    <DIR>          .
06/24/2020  02:17 AM    <DIR>          ..
06/24/2020  02:17 AM            14,203 15055
06/24/2020  02:17 AM            10,129 15168
               2 File(s)         24,332 bytes

 Directory of C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.defa
ult-beta\cache2\trash22085

06/24/2020  02:21 AM    <DIR>          .
06/24/2020  02:21 AM    <DIR>          ..
               0 File(s)              0 bytes
```

host view is:
```
 Directory of c:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.defa
ult-beta\cache2\trash17007

06/24/2020  02:17 AM    <DIR>          .
06/24/2020  02:17 AM    <DIR>          ..
06/24/2020  02:17 AM            14,203 15055
06/24/2020  02:17 AM            10,129 15168
               2 File(s)         24,332 bytes
```
and the dirs and files are all encrypted ("e" in total commander) which might be important to know because as I've mentioned before, deleting an "e" file from within sandbox will give access denied and not delete it.


and host view(via total commander) of the sandbox location is:
![1](https://user-images.githubusercontent.com/66539662/85490947-2f4bc880-b5c2-11ea-8c2a-9c6058cc27f5.jpg)
![2](https://user-images.githubusercontent.com/66539662/85490949-2fe45f00-b5c2-11ea-8274-f4974c3a812f.jpg)
![3](https://user-images.githubusercontent.com/66539662/85490952-307cf580-b5c2-11ea-9cee-29862c56d879.jpg)


As I was writing this however the loop stopped because deletion no longer "succeeded" but instead it gave `GetLastError()` of 32 (ERROR_SHARING_VIOLATION    32 (0x20)    The process cannot access the file because it is being used by another process.) most likely while I was trying to list the contents of the dirs above.

<details>

```
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 Succeeded in removing dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove() - Returning directory trash22085
[Parent 18856: Cache2 I/O]: D/cache2 got nothing more to enumerate
[Parent 18856: Cache2 I/O]: D/cache2 no more stuff to enumerate, so removing parent dir (non-recursive) 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 failed(32) to remove dir 'C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085'
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::RemoveTrashInternal() - Cannot remove trashdir. [name=trash22085]
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::FindTrashDirToRemove()
[Parent 18856: Cache2 I/O]: D/cache2 CacheFileIOManager::RemoveTrashInternal() - No trash directory found.
[Parent 18856: Main Thread]: D/cache2 CacheEntryHandle::Dismiss 000000001991F720
[Parent 18856: Main Thread]: D/cache2   already dropped
[Parent 18856: Main Thread]: D/cache2 CacheEntryHandle::~CacheEntryHandle 000000001991F720
[Parent 18856: Main Thread]: D/cache2 CacheEntryHandle::Dismiss 0000000018EF7180
[Parent 18856: Main Thread]: D/cache2   already dropped
[Parent 18856: Main Thread]: D/cache2 CacheEntryHandle::~CacheEntryHandle 0000000018EF7180
[Parent 18856: Main Thread]: D/cache2 CacheEntryHandle::Dismiss 0000000018ED0BA0
[Parent 18856: Main Thread]: D/cache2   already dropped
[Parent 18856: Main Thread]: D/cache2 CacheEntryHandle::~CacheEntryHandle 0000000018ED0BA0
```

</details>

Is this helpful?
Want me to do something else? (since I've easy way to add new changes to firefox now)
I know I can probably try to always remove the dir recursively(by changing a [false](https://searchfox.org/mozilla-central/rev/46e3b1ce2cc120a188f6940b5c6eab6b24530e4f/netwerk/cache2/CacheFileIOManager.cpp#3395) to a true), that might be a workaround for this issue that Firefox could implement... Haven't yet tried to do this because if it works, it may take a while to reproduce the issue again. I still haven't figured out how to reproduce it, but it definitely needs both outside and inside the sandbox firefox runs! (tho not concurrently)

**Comment by menaquinoneK2** [comment]
Can't help but notice that, unless I'm missing something, if the sandbox view of dir `trash22085` shows it as empty, doesn't that means that the host view of c:\sandbox\... location of the same dir should also show empty? yet it shows two 0 byte files inside it. Alternatively shouldn't these files also be visible inside sandbox then? Again, I may be missing something...

**Comment by DavidXanatos** [comment]
wowo compiling your own firefox... respect... 
was t strait forwards or a lot of hunting down dependencies?

Ok so the way it works if you delete a file inside sandboxie that exists on the host is that sandboxie creates a file in the sandboxed location that has a special attribute set marking if it finds that special file it means don't show the real file from the host.

I think the problem is really the encrypted attribute, I will do some tests with using that feature.

Thats very valuable information thank you.

**Comment by menaquinoneK2** [comment]
I could look further into this if I knew how to compile sandboxie (ideally with VS2019, unless it really requires VS2015). Any pointers?

**Comment by DavidXanatos** [comment]
Well first of VS 2019 allows you ton install a 2017 and a 2015 compiler toolset,
so you can use a 2019 installation just fine. I'm currently using 2017 myself.
the only old thing you need for sandboxie is the Window 7.1 DDK

Currently I'm using Qt5.11.2 for SandMan.exe but any newer should work as well.

Cheers
David X.

**Comment by menaquinoneK2** [comment]
Thanks! I've like zero experience with visual studio stuff but I finally managed to compile it (didn't run it yet tho, unsure even how to do that, do I need to make it into an install form and then install it? since I already have the normal/upstream sandboxie installed via installer...).

So, firefox is calling `RemoveDirectoryW(some_trash_dir's_name_here)` which returns non-zero from within sandboxie indicating that it did remove it aka that function succeeded, but in fact it doesn't, which is why the whole `while true` loop never exits.

Could you tell me where inside sandboxie is the code that traps/hooks this function, so I can check to see why it returns non-zero(aka succeeded to remove the dir) when in fact it doesn't remove it ? 
The only relevant result I could find is the following, is this it?
https://github.com/sandboxie-plus/Sandboxie/blob/f00ef56eda2a09a8a533f5a5469580c1697c3bf8/Sandboxie/apps/start/delete.cpp#L879

PS: `some_trash_dir's_name_here` is actually an empty dir when seen from within sandbox, but it contains two 0byte files when seen from host by looking inside c:\sandbox\... directly. In [that comment](https://github.com/sandboxie-plus/Sandboxie/issues/32#issuecomment-648547629), it's `trash22085`.

**Comment by menaquinoneK2** [comment]
Ok so just for the record, the workaround is to enter(`chdir`), from within the sandbox, into the specific problematic trash dir(`trash22085` in my case) from command prompt(`cmd.exe`). This will immediately break the loop because it causes firefox to no longer get a success when trying to remove that dir, due to sharing violation.

ie. same as this:
```
C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache
2>rmdir trash22085

C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache
2>dir
 Volume in drive C has no label.
 Volume Serial Number is 1111-2222

 Directory of C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.defa
ult-beta\cache2

06/27/2020  15:33 PM    <DIR>          .
06/27/2020  15:33 PM    <DIR>          ..
06/27/2020  15:34 PM    <DIR>          doomed
06/27/2020  15:34 PM    <DIR>          entries
06/27/2020  15:33 PM            42,451 index
06/24/2020  02:19 AM            14,723 index.log
06/27/2020  14:55 PM    <DIR>          mii
06/27/2020  14:59 PM    <DIR>          shit
06/24/2020  02:17 AM    <DIR>          trash17007
06/24/2020  02:21 AM    <DIR>          trash22085
               2 File(s)         57,174 bytes
               8 Dir(s)   6,293,266,432 bytes free

C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache
2>dir trash22085
 Volume in drive C has no label.
 Volume Serial Number is 1111-2222

 Directory of C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.defa
ult-beta\cache2\trash22085

06/24/2020  02:21 AM    <DIR>          .
06/24/2020  02:21 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)   6,293,164,032 bytes free

```
(see? no error(ie. success), yet it didn't remove the empty dir)

now to get an error:
do this in a new terminal:
```
C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache
2>cd trash22085
```
now run that again in the original terminal:
```
C:\Users\John\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache
2>rmdir trash22085
The process cannot access the file because it is being used by another process.
```
and bam, the firefox loop is broken this way.

So according to that code(however I haven't yet figured out how to printf or run stuff) that I've mentioned in an edit in the prev. comment, sandboxie not seeing any files within that dir(I guess?), will return success, even though it didn't delete the dir somehow. I'll have to figure out how to debug that part(but not with a debugger heh), possibly using `OutputDebugString` (tho I've no idea where I'd see its output...

**Comment by DavidXanatos** [comment]
OutputDebugString youls print to visual studios output window,
or oyu can use a tool like dbgview.exe from sys internals or task explorer to view the debug output

when you have compiled it you need to replace teh files you changed in your original sandboxie instalation, as long as you dont change teh driver that does not need the kmdutill.exe or a reboot just stop sbiesvc and replace what you need

**Comment by menaquinoneK2** [comment]
Thank you for that useful info! I was compiling successfully Sandboxie-Plus thus far, but Sandboxie itself was another pain of failures(but then I realized I should've set to Release and x64).

Anyway, I've tracked down the issue to a bafflingly succeeding call to `__sys_NtCreateFile` (which is presumably the unhooked version of `NtCreateFile`) which tries to delete-on-handle_close the dir `\Device\HarddiskVolume2\Sandbox\John\DefaultBox\user\current\AppData\Local\Mozilla\Firefox\Profiles\dosekefd.default-beta\cache2\trash22085` (which is correct path).

the code reached is exactly this:
https://github.com/sandboxie-plus/Sandboxie/blob/f22ec96fb1a1fe867bd040ca08b001eb18b864c2/Sandboxie/core/dll/file.c#L3062-L3069

and that call freakin' succeeds!!! and yet the dir isn't deleted(well, it can't delete it, really because that dir is not empty in that path I mentioned above, it has two 0 byte files inside it, the call should fail with directory not empty or something! however that dir inside the sandbox is empty, but inside the sandbox it does have a very different path) 
but why doesn't it fail? 
Also what is setting the value for the function __sys_NtCreateFile which is initially a [NULL function](https://github.com/sandboxie-plus/Sandboxie/blob/f22ec96fb1a1fe867bd040ca08b001eb18b864c2/Sandboxie/core/dll/file.c#L266) ? (I couldn't figure this one out, but presumably it is set by "something" correctly to point to the original and unhooked NtCreateFile ? so this doesn't matter much, if it is so...)

Basically there's nothing else I can do now, that call to the unhooked NtCreateFile succeeds when it shouldn't ... I cannot comprehend!

**Comment by rugabunda** [comment]
Well its been over a week and I have not seen this issue re-surface... so something has definitely changed in the code because this was a very persistent bug for me!

**Comment by rugabunda** [comment]
bump, to this day haven't had any issue;

**Comment by rugabunda** [comment]
Closing for now, have not seen any cpu use problem for a LONG time. tx everybody.

**Comment by codesmashd** [comment]
I'm using the latest version, 5.46.4 on Windows 10 and this issue still happens with me (started way back when sophos was supporting it), although it's simple to fix by deleting the trash folders. A potential explanation I can come up with is Firefox updates. When I recently updated it from 84.0.2 to 85 outside of the sandbox, all sandboxes that have previously created instances of Firefox now have trash folders that need to be manually removed or it would suck up CPU at 30+%. There may be other situations where this occurs (My memory is fuzzy because I just delete them when I notice the computer running slow).

From my experience, this workaround (deleting trash folders) also worked on 5.33.6 for extended periods until something creates them again.

**Comment by mysteriously** [comment]
I think it still happens

**Comment by mailinglists35** [comment]
I don't use sandboxie, but since this is the only useful result, I'm adding this comment that firefox.exe still drains my laptop battery, with top thread being "ucrtbase.dll!thread_start<unsigned int (__cdecl*)(void *),1>".

I don't see any trash files/folders in the cache2 folder

firefox idle: 1% cpu
edge idle: 0.1% cpu.
this 0.9 percent is big enough to not allow the cpu sleep and draw more current.

hoping this info confirms someone elses' pursue of a perfect firefox friendly with energy. but I think there is something rotten deep inside firefox core architecture, since I can observe this constant low cpu usage on idle for all os where I use it (linux, macos, windows)
