### ISSUE TITLE
SBIE2314 for certain programs under Windows 7 64Bit Professional since Sandboxie-Plus v. 0.5.4c

### ISSUE THREAD

**Issue by FlipeGarcia** [sandboxie-plus/Sandboxie#449]
At least

i) Comodo Dragon Chrome version (https://www.comodo.com/home/browsers-toolbars/browser.php), and
ii) Lightbulb (https://github.com/Tyrrrz/LightBulb),

both forced sandboxed programs and which used to worked without problems up to version 0.5.4b, stop working as soon as I upgrade to any newer version, whereas reverting back to this version solve the problem again.

In particular, shortly after Lightbulb is opened at startup it gets forcibly closed with a SBIE2314 message by Sandboxie.
Similarly, if I try to open the Dragon browser and access a page, Sandboxie behaves in the same manner.

Should I change something in the previous configuration, which I think I have since the original Sandboxie, or is it a bug?

Thanks for the help and to David for keeping this program alive!

The corresponding ini sections are:

> [Comodo Dragon]
> ConfigLevel=7
> AutoRecover=y
> BlockNetworkFiles=y
> Template=AutoRecoverIgnore
> Template=Firefox_Phishing_DirectAccess
> Template=Chrome_Phishing_DirectAccess
> Template=LingerPrograms
> Template=BlockPorts
> Template=WindowsFontCache
> Template=qWave
> Template=Dragon_Force
> Template=Dragon_Bookmarks_DirectAccess
> Template=Dragon_History_DirectAccess
> Template=Dragon_Cookies_DirectAccess
> Template=Dragon_Preferences_DirectAccess
> Template=Dragon_Profile_DirectAccess
> RecoverFolder=%Desktop%
> RecoverFolder=%Favorites%
> RecoverFolder=%Personal%
> BorderColor=#00FFFF,ttl
> Enabled=y
> CopyLimitKb=49152
> CopyLimitSilent=y
> ReadFilePath=C:\Program Files (x86)\Windows Defender\
> ReadFilePath=C:\Program Files (x86)\Realtek\
> ReadFilePath=C:\ProgramData\VirtualBox\
> ReadFilePath=C:\Program Files (x86)\Microsoft.NET\
> ReadFilePath=C:\ProgramData\Microsoft\
> ReadFilePath=C:\Program Files (x86)\ASM106xSATA\
> ReadFilePath=C:\Program Files (x86)\Intel\
> ReadFilePath=C:\Program Files (x86)\Avira\
> ReadFilePath=C:\Program Files\
> ReadFilePath=C:\Windows\
> OpenPipePath=%Local AppData%\Comodo\Dragon\
> OpenPipePath=%AppData%\Comodo\Dragon
> OpenPipePath=F:\Downloads\
> NeverDelete=y
> 
> [Lightbulb]
> Enabled=y
> ConfigLevel=7
> AutoRecover=y
> BlockNetworkFiles=y
> Template=qWave
> Template=WindowsFontCache
> Template=BlockPorts
> Template=LingerPrograms
> Template=Chrome_Phishing_DirectAccess
> Template=Firefox_Phishing_DirectAccess
> Template=AutoRecoverIgnore
> RecoverFolder=%Personal%
> RecoverFolder=%Favorites%
> RecoverFolder=%Desktop%
> BorderColor=#00FFFF,ttl
> ForceFolder=D:\PortableApps\SystemTools\LightBulb
> NotifyInternetAccessDenied=n
> OpenFilePath=D:\PortableApps\SystemTools\LightBulb
> NeverDelete=y

**Comment by DavidXanatos** [comment]
strange on my system lightbulb starts just fine...

what does the SBIE2314 says exactly?

**Comment by FlipeGarcia** [comment]
Thanks for checking it. These are the errors that I get (first for LightBulb, later for Dragon):

![screenshot 1](https://user-images.githubusercontent.com/5088025/106048255-ef633b80-60e4-11eb-8341-f625cba3724e.jpg)

**Comment by DavidXanatos** [comment]
thanks,

are you absoluely sure that the break is from 0.5.4b to 0.5.4c?
Just asking as there are no obvius changed that  I would expect to break something.

**Comment by DavidXanatos** [comment]
i have found the bug I think, it should be fixed in the next build.

**Comment by FlipeGarcia** [comment]
> i have found the bug I think, it should be fixed in the next build.

Great! Thanks, David!

> are you absoluely sure that the break is from 0.5.4b to 0.5.4c?
> Just asking as there are no obvius changed that I would expect to break something.

I guess the information is no longer relevant, but, just in case, I tested again installing one after the other and yes, the break occurs from 0.5.4b to 0.5.4c

**Comment by FlipeGarcia** [comment]
Hi David,
I am not sure whether it was in the version you uploaded yesterday that the problem was supposed to be solved. I have just installed it and the problem remains:

LightBulb.exe (2432): SBIE2101 Object name not found: \RPC Control\LRPC-909efb3f71d229f5df, error AlpcConnectPort (C0000022) access=001F0001 initialized=1

followed by many SBIE2314 messages which closes the  program. The same behavior with Dragon.

As usual, I have reset the sandboxes just in case, but no change.

**Comment by FlipeGarcia** [comment]
Hi David,
I am not sure whether it was in the version you uploaded yesterday that the problem was supposed to be solved. I have just installed it and the problem remains:

LightBulb.exe (2432): SBIE2101 Object name not found: \RPC Control\LRPC-909efb3f71d229f5df, error AlpcConnectPort (C0000022) access=001F0001 initialized=1

followed by many SBIE2314 messages which closes the  program. The same behavior with Dragon.

As usual, I have reset the sandboxes just in case, but no change.

**Comment by FlipeGarcia** [comment]
Hi David,
I am not sure whether it was in the version you uploaded yesterday that the problem was supposed to be solved. I have just installed it and the problem remains:

LightBulb.exe (2432): SBIE2101 Object name not found: \RPC Control\LRPC-909efb3f71d229f5df, error AlpcConnectPort (C0000022) access=001F0001 initialized=1

followed by many SBIE2314 messages which closes the  program. The same behavior with Dragon.

As usual, I have reset the sandboxes just in case, but no change.

**Comment by FlipeGarcia** [comment]
Hi David,
I am not sure whether it was in the version you uploaded yesterday that the problem was supposed to be solved. I have just installed it and the problem remains:

LightBulb.exe (2432): SBIE2101 Object name not found: \RPC Control\LRPC-909efb3f71d229f5df, error AlpcConnectPort (C0000022) access=001F0001 initialized=1

followed by many SBIE2314 messages which closes the  program. The same behavior with Dragon.

As usual, I have reset the sandboxes just in case, but no change.

**Comment by FlipeGarcia** [comment]
Hi David,
I am not sure whether it was in the version you uploaded yesterday that the problem was supposed to be solved. I have just installed it and the problem remains:

LightBulb.exe (2432): SBIE2101 Object name not found: \RPC Control\LRPC-909efb3f71d229f5df, error AlpcConnectPort (C0000022) access=001F0001 initialized=1

followed by many SBIE2314 messages which closes the  program. The same behavior with Dragon.

As usual, I have reset the sandboxes just in case, but no change.
