### ISSUE TITLE
VP9 Hardware Acceleration Broken for Firefox and Edge

### ISSUE THREAD

**Issue by N8Z7JMYLU** [sandboxie-plus/Sandboxie#742]
This is an issue that has been persistent across many version of Windows 10 and Sandboxie for years but to my knowledge not investigated yet.

### Short summary: VP9 video hardware acceleration reverts to software decoding for sites like Youtube when Firefox is sandboxed. The hardware is perfectly capable of utilizing hardware decoding once running without Sandboxie. Note, H264 is being properly processed with acceleration.

Current system:
Windows 10 - 20H2
Intel N5000 / UHD Graphics 605
Firefox 87.0
Sandboxie Classic 5.49.5

### Steps taken to test for configuration impact on the issue so far:

- Started with a fresh (portable) Firefox profile
- Started with a fresh Sandbox with default settings
- Gave direct access to all sandboxed processed for IPC
- Gave full window access to all sandboxed processes

**Comment by xame-arch** [comment]
Maybe try logging between the working and non-working computers and also try in the non-working computer to create a new sandbox with (right click - sandbox setup - resource access - add program - direct access - add program - full access - add program - registry access - add program - IPC access - add program - windows access) the program could be the browser or the Intel driver or both for Tor 32 bit adding Open to it helped me, maybe it will troubleshoot in this case also make logs.
I have a video to help with logging
https://www.youtube.com/watch?v=wXFpo78712M

**Comment by DavidXanatos** [comment]
is this still broken with 0.8.1 ?

**Comment by N8Z7JMYLU** [comment]
No change since the initial report with Classic 5.53.3 and the latest Firefox. However it doesn't seem isolated to Firefox as sandboxing Microsoft Edge also blocks VP9 acceleration support.

There seems to be a general problem with anything GPU related as websites that make use of WebGL are sluggish and low in performance while sandboxed.

**Comment by DavidXanatos** [comment]
this shoudl be fixed in the 1.0x lien of builds
if its stil happens for some program try
AlwaysUseWin32kHooks=program.exe,y
and write here that its needed and or which program
for chrome and alike its on autoamtically

**Comment by N8Z7JMYLU** [comment]
Tested inside a new Sandbox with 1.0.9 installed. Unfortunately still the same with either MS Edge or Firefox.

**Comment by DavidXanatos** [comment]
even when you add
AlwaysUseWin32kHooks=y
to the sandbox config?

**Comment by N8Z7JMYLU** [comment]
Indeed, I had explicitly added this to make sure the option was enabled.

This is Sandboxed versus running without Sandboxie:
![Sandboxed](https://i.imgur.com/fwOrvL9.jpg)

![Unsandboxed](https://i.imgur.com/tPP06Vd.jpg)

**Comment by DavidXanatos** [comment]
hmm... isee I'll take a look into it, the issue is that debuging siuch things in a VM is not so great as tehre the GPU is fake and many things defualt anyways to CPU rendering

**Comment by N8Z7JMYLU** [comment]
Are there any kind of logs I could provide that would be useful?

**Comment by mysteriously** [comment]
FF 91.5.1esr x64. First video starts 5-15 seconds after pressing play. Sometimes there is only black screen and it is not played at all. Restarting FF few times fixes it.

**Comment by DavidXanatos** [comment]
hmm... that might be more difficult than anticipated.

so you can get it to work if you
1. remove RpcMgmtSetComTimeout=y from the Templates.ini
2. open com and disable use of RpcMgmtSetComTimeout in the advanced tab
3. switch the box to compartment mode (reduced isoaltion)

then for me firefox's gpu acceleration for video playback starts working again.

please confirm.

**Comment by N8Z7JMYLU** [comment]
Unfortunately I am unable to complete those steps. If this method were to work would be possible to implement it into future releases so this workaround isn't necessary?

**Comment by isaak654** [comment]
1. `UseRpcMgmtSetComTimeout=AppXDeploymentClient.dll,y` is turned off since Sandboxie [v1.0.10 / 5.55.10](https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.10)

> removed UseRpcMgmtSetComTimeout=AppXDeploymentClient.dll,y used for Free Download Manager as it broke other things
-- only if you use Free Download Manager together with the setting RpcMgmtSetComTimeout=n in a sandbox, you have to add the line manually to your Sandboxie.ini

About 2 and 3, those options are already available in the Plus edition. You won't find them in Sandboxie Classic because the lead developer's goal is to encourage as many people as possible to adopt the Plus interface. However, they can be configured manually in the Sandboxie.ini configuration file.

**Comment by mysteriously** [comment]
Guys what is the latest SBIE version which does not cause fallback to software decoding for Firefox and also which does not have black screen/spinning circle issue when we try to play any video file?

**Comment by mysteriously** [comment]
Spinning circle for 30 seconds on YT and many other video websites.
Dropping to software playback mode.
Lags and not smooth playback
Videos refuse to play when paused and resumed.

![image](https://user-images.githubusercontent.com/17072890/179699763-05f9d498-aa9d-4948-ba14-587a6f6a7c6d.png)

**Comment by mysteriously** [comment]
I gave up and switched to Edge for viewing videos.
Firefox had issues with playing 1080p and 2x 480p videos.
Edge is able to handle 3x1080p with only a little lag when entering full screen

**Comment by W1K23** [comment]
I have the same problem.
I also asked on the [xanasoft forum](https://forum.xanasoft.com/viewtopic.php?f=16&t=570&sid=868c173ee895e95da8b0615c6ba14fa8), but the developer wrote that this isn't a bug, this is how Sandboxie works.
I can't watch YouTube 4K videos in Sandboxie because the CPU gets very hot, 90-100°C and the fan spins strongly. (notebook)
Outside of the Sandboxie, 4K videos run smoothly, low CPU with 7-10% load, max temp 50-60°C and the machine is quiet.
I'm very sad. I can't believe there isn't a setting for this. It's okay if it comes at the expense of security a little. I cannot browse normally without HW acceleration. I can't believe the browser can't be forced to HW acceleration.
The Green box is not a solution for me. 
- [Youtube 4 K video without SB.  CPU 55°C, usage 4-8%](https://cdn.rios.hu/dl/upc/2023-05/29723_ffsiman.jpg)
- [Same video in SBoxie. CPU 91°C, 35%](https://cdn.rios.hu/dl/upc/2023-05/29723_ffsboxieban2.jpg)

**Comment by W1K23** [comment]
[https://github.com/sandboxie-plus/Sandboxie/issues/3102](url)

The issue remains unresolved, there is still no HW acceleration in Firefox when running in SBoxie! Chromium browsers don’t have this issue. According to the developer it’s due to security reasons, but that’s nonsense, because if that were the case there would be no HW acc. in chromium browsers either when running them in SBoxie. The topic shouldn’t be closed, the developer should fix it already. He should solve the problem, because for over a year I haven’t been able to use Firefox because of this! 
The developer hasn’t fixed it for years! I’ve asked multiple times and he responded that he doesn’t care, doesn’t have time, doesn’t use Firefox and that I should use another browser etc. I don’t understand this at all. :\

**Comment by pulsarclarinetokrabee** [comment]
Especially with the upcoming changes to Chromium based browsers regarding Manifest V3, having a fully functioning alternative becomes more relevant.

I would ask for this issue to be given a new look, with a possible solution that comes built-in to Sandboxie.

**Comment by githubusername2024** [comment]
You can use MS Edge instead of Chrome. It has its own set of issues, especially on Win11 24H2 (same issues like 23H2 had after release; tabs show black screen, msedge.exe does not terminate in SBIE).

**Comment by dhjw** [comment]
I would love to be able to install the VP9 codec in Sandboxie-Plus as I have a game with VP9 cut-scenes (Returnal). I found an appxBundle with it but unfortunately add-AppxPackage in an admin powershell throws an error about console output, and copying the dll from the appx bundle or recreating everything matching msvp9* from the host system to the sandbox doesn't seem to help (maybe needed some registry entries too?).
